# Generated by Django 5.2.5 on 2026-04-28 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0010_alter_animalevent_animal"),
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatmentrecord",
            name="animal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treatments",
                to="animals.animal",
            ),
        ),
    ]
