# Generated by Django 5.2.5 on 2026-07-25 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0007_healthalert"),
        ("pharmacy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentrecord",
            name="administered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="administered_treatments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="treatmentrecord",
            name="administration_route",
            field=models.CharField(
                blank=True,
                choices=[
                    ("oral", "Oral"),
                    ("injection", "Injection"),
                    ("topical", "Topical"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="treatmentrecord",
            name="dose",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="treatmentrecord",
            name="drug",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treatments",
                to="pharmacy.drug",
            ),
        ),
        migrations.AddField(
            model_name="treatmentrecord",
            name="drug_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treatments",
                to="pharmacy.drugbatch",
            ),
        ),
        migrations.AddField(
            model_name="treatmentrecord",
            name="duration_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treatmentrecord",
            name="frequency",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="treatmentrecord",
            name="next_dose_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treatmentrecord",
            name="prescribed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescribed_treatments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="treatmentrecord",
            name="quantity_administered",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="treatmentrecord",
            name="treatment_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="treatmentrecord",
            name="withdrawal_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
