# Generated by Django 5.2.5 on 2026-08-31 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0011_healthcase_healthobservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentrecord",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="treatments",
                to="health.healthcase",
            ),
        ),
    ]
