# Generated by Django 5.2.5 on 2026-09-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_normalize_role_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='mobile_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='system_template_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='web_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
