# Generated by Django 5.2.5 on 2026-03-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmunit",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="farmunit",
            name="unit_type",
            field=models.CharField(
                choices=[("pen", "Pen"), ("barn", "Barn"), ("pond", "Pond")],
                max_length=50,
            ),
        ),
    ]
