# Generated by Django 5.2.5 on 2026-07-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_passwordresetotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresetotp",
            name="reset_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="passwordresetotp",
            name="token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passwordresetotp",
            name="token_used",
            field=models.BooleanField(default=False),
        ),
    ]
