# Generated by Django 5.2.5 on 2026-04-01 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_alter_organization_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmtype",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farm_types",
                to="organization.industry",
            ),
        ),
    ]
