# Generated by Django 5.2.5 on 2026-09-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
