# Generated by Django 5.2.5 on 2026-07-25 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0007_weightreferencerange"),
        ("movement_records", "0004_add_housing_unit_to_movement"),
        ("organization", "0004_farmtype_industry"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_sale_weight_kg", models.FloatField(blank=True, null=True)),
                ("min_sale_age_months", models.FloatField(blank=True, null=True)),
                ("approaching_ready_threshold_pct", models.FloatField(default=85)),
                ("sale_recommended_margin_pct", models.FloatField(default=15)),
                ("allow_pregnant_sale", models.BooleanField(default=False)),
                ("require_sale_approval", models.BooleanField(default=False)),
                ("expected_sale_expenses_pct", models.FloatField(default=0)),
                ("is_system", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_policies",
                        to="admin_panel.livestockbreed",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_policies",
                        to="organization.farm",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_policies",
                        to="admin_panel.livestockspecies",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("species", "breed", "farm"),
                        name="unique_sale_policy_scope",
                    )
                ],
            },
        ),
    ]
