# Generated by Django 5.2.5 on 2026-09-05 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_panel", "0001_initial"),
        ("animals", "0001_initial"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="animallifecyclehistory",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lifecycle_history",
                to="animals.animal",
            ),
        ),
        migrations.AddField(
            model_name="animallifecyclehistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lifecycle_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="farmhousingunit",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="housing_units",
                to="organization.farm",
            ),
        ),
        migrations.AddField(
            model_name="livestockbreed",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_breeds",
                to="organization.farm",
            ),
        ),
        migrations.AddField(
            model_name="livestockbreed",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="livestock_breeds",
                to="admin_panel.livestockspecies",
            ),
        ),
        migrations.AddField(
            model_name="lifestagedefinition",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="life_stages",
                to="admin_panel.livestockspecies",
            ),
        ),
        migrations.AddField(
            model_name="housingunittype",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="housing_unit_types",
                to="admin_panel.livestockspecies",
            ),
        ),
        migrations.AddField(
            model_name="farmhousingunit",
            name="allowed_species",
            field=models.ManyToManyField(
                blank=True,
                related_name="housing_units",
                to="admin_panel.livestockspecies",
            ),
        ),
        migrations.AddField(
            model_name="animalclassification",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classifications",
                to="admin_panel.livestockspecies",
            ),
        ),
        migrations.AddField(
            model_name="breed",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breeds",
                to="admin_panel.species",
            ),
        ),
        migrations.AddField(
            model_name="weightreferencerange",
            name="breed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weight_ranges",
                to="admin_panel.livestockbreed",
            ),
        ),
        migrations.AddField(
            model_name="weightreferencerange",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weight_ranges",
                to="organization.farm",
            ),
        ),
        migrations.AddField(
            model_name="weightreferencerange",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weight_ranges",
                to="admin_panel.livestockspecies",
            ),
        ),
        migrations.AddConstraint(
            model_name="livestockbreed",
            constraint=models.UniqueConstraint(
                fields=("species", "farm", "name"), name="unique_breed_per_species_farm"
            ),
        ),
        migrations.AddConstraint(
            model_name="lifestagedefinition",
            constraint=models.UniqueConstraint(
                fields=("species", "name"), name="unique_life_stage_per_species"
            ),
        ),
        migrations.AddConstraint(
            model_name="housingunittype",
            constraint=models.UniqueConstraint(
                fields=("species", "name"), name="unique_housing_unit_type_per_species"
            ),
        ),
        migrations.AddConstraint(
            model_name="animalclassification",
            constraint=models.UniqueConstraint(
                fields=("species", "sex", "name"),
                name="unique_classification_per_species_sex",
            ),
        ),
    ]
