# Generated by Django 5.2.5 on 2026-07-16 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_unittype"),
        ("organization", "0004_farmtype_industry"),
    ]

    operations = [
        migrations.CreateModel(
            name="LivestockSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ruminant", "Ruminant"),
                            ("monogastric", "Monogastric"),
                            ("small_livestock", "Small Livestock"),
                            ("equine", "Equine"),
                            ("camelid", "Camelid"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Livestock Species",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HousingUnitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="housing_unit_types",
                        to="admin_panel.livestockspecies",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FarmHousingUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="housing_units",
                        to="organization.farm",
                    ),
                ),
                (
                    "unit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="farm_units",
                        to="admin_panel.housingunittype",
                    ),
                ),
                (
                    "allowed_species",
                    models.ManyToManyField(
                        blank=True,
                        related_name="housing_units",
                        to="admin_panel.livestockspecies",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AnimalClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifications",
                        to="admin_panel.livestockspecies",
                    ),
                ),
            ],
            options={
                "ordering": ["species", "sex", "name"],
            },
        ),
        migrations.CreateModel(
            name="LivestockBreed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("origin", models.CharField(blank=True, max_length=100, null=True)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_breeds",
                        to="organization.farm",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livestock_breeds",
                        to="admin_panel.livestockspecies",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("species", "farm", "name"),
                        name="unique_breed_per_species_farm",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="housingunittype",
            constraint=models.UniqueConstraint(
                fields=("species", "name"), name="unique_housing_unit_type_per_species"
            ),
        ),
        migrations.AddConstraint(
            model_name="animalclassification",
            constraint=models.UniqueConstraint(
                fields=("species", "sex", "name"),
                name="unique_classification_per_species_sex",
            ),
        ),
    ]
