# Generated by Django 5.2.5 on 2026-07-25 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0005_newsletter_subscriber"),
        ("animals", "0024_animal_breeding_restricted_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalLifecycleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_stage",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("new_stage", models.CharField(max_length=50)),
                ("is_override", models.BooleanField(default=False)),
                ("override_reason", models.TextField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifecycle_history",
                        to="animals.animal",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lifecycle_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Animal Lifecycle History",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="LifeStageDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                ("min_age_months", models.FloatField(blank=True, null=True)),
                ("max_age_months", models.FloatField(blank=True, null=True)),
                ("min_weight_kg", models.FloatField(blank=True, null=True)),
                ("max_weight_kg", models.FloatField(blank=True, null=True)),
                (
                    "applicable_sex",
                    models.CharField(
                        choices=[
                            ("any", "Any"),
                            ("male", "Male"),
                            ("female", "Female"),
                        ],
                        default="any",
                        max_length=10,
                    ),
                ),
                ("requires_pregnant", models.BooleanField(blank=True, null=True)),
                ("requires_lactating", models.BooleanField(blank=True, null=True)),
                ("is_system", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_stages",
                        to="admin_panel.livestockspecies",
                    ),
                ),
            ],
            options={
                "ordering": ["species", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("species", "name"), name="unique_life_stage_per_species"
                    )
                ],
            },
        ),
    ]
