# Generated by Django 5.2.5 on 2026-07-29 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0007_weightreferencerange"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmhousingunit",
            name="unit_type",
        ),
    ]
