# Generated by Django 5.2.5 on 2026-03-19 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="farm",
            name="farm_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="organization.farmtype"
            ),
        ),
    ]
