# Generated by Django 5.2.5 on 2026-07-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_farmtype_industry"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="organizations/"),
        ),
    ]
