# Generated by Django 5.2.5 on 2026-06-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movement_records", "0002_alter_movementrecord_options_salesrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("recorded", "Recorded"),
                    ("approved", "Approved"),
                    ("corrected", "Corrected"),
                ],
                default="recorded",
                max_length=20,
            ),
        ),
    ]
