# Generated by Django 5.2.5 on 2026-07-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_livestock_master_data"),
        ("movement_records", "0003_add_status_to_sales_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="movementrecord",
            name="from_housing_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movement_from_records",
                to="admin_panel.farmhousingunit",
            ),
        ),
        migrations.AddField(
            model_name="movementrecord",
            name="to_housing_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movement_to_records",
                to="admin_panel.farmhousingunit",
            ),
        ),
    ]
