# Generated by Django 5.2.5 on 2026-03-26 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_unittype"),
        ("farms", "0002_alter_farmunit_status_alter_farmunit_unit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmunit",
            name="unit_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="farm_unit",
                to="admin_panel.unittype",
            ),
        ),
    ]
