# Generated by Django 5.2.5 on 2026-06-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0005_mortalityrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="mortalityrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("recorded", "Recorded"),
                    ("approved", "Approved"),
                    ("corrected", "Corrected"),
                ],
                default="recorded",
                max_length=20,
            ),
        ),
    ]
