# Generated by Django 5.2.5 on 2026-07-25 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0008_treatmentrecord_administered_by_and_more"),
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentrecord",
            name="external_drug_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="treatmentrecord",
            name="external_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treatmentrecord",
            name="external_source",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="treatmentrecord",
            name="external_unit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="treatmentrecord",
            name="external_unit_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="treatmentrecord",
            name="is_external_administration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="treatmentrecord",
            name="reconciled_to_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reconciled_treatments",
                to="pharmacy.drugbatch",
            ),
        ),
    ]
