# Generated by Django 5.2.5 on 2026-07-25 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0025_animal_sale_approved_animal_sale_approved_at_and_more"),
        ("health", "0009_treatmentrecord_external_drug_name_and_more"),
        ("organization", "0004_farmtype_industry"),
        ("pharmacy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="healthalert",
            name="drug_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_alerts",
                to="pharmacy.drugbatch",
            ),
        ),
        migrations.AddConstraint(
            model_name="healthalert",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("drug_batch", "alert_type"),
                name="unique_open_alert_per_batch_type",
            ),
        ),
    ]
