# Generated by Django 5.2.5 on 2026-07-25 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0006_animallifecyclehistory_lifestagedefinition"),
        ("organization", "0004_farmtype_industry"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeightReferenceRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("any", "Any"),
                            ("male", "Male"),
                            ("female", "Female"),
                        ],
                        default="any",
                        max_length=10,
                    ),
                ),
                (
                    "production_purpose",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("min_age_months", models.FloatField(blank=True, null=True)),
                ("max_age_months", models.FloatField(blank=True, null=True)),
                ("min_weight_kg", models.FloatField(blank=True, null=True)),
                ("max_weight_kg", models.FloatField(blank=True, null=True)),
                ("target_daily_gain_kg", models.FloatField(blank=True, null=True)),
                ("is_system", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "breed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_ranges",
                        to="admin_panel.livestockbreed",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_ranges",
                        to="organization.farm",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_ranges",
                        to="admin_panel.livestockspecies",
                    ),
                ),
            ],
            options={
                "ordering": ["species", "min_age_months"],
            },
        ),
    ]
