# Generated by Django 5.2.5 on 2026-04-09 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_panel", "0002_unittype"),
        ("farms", "0003_alter_farmunit_unit_type"),
        ("organization", "0004_farmtype_industry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tag_id", models.CharField(max_length=100, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("born", "Born"),
                            ("purchased", "Purchased"),
                            ("imported", "Imported"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("estimated_age_months", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pregnant", "Pregnant"),
                            ("lactating", "Lactating"),
                            ("sick", "Sick"),
                            ("quarantine", "Quarantine"),
                            ("sold", "Sold"),
                            ("dead", "Dead"),
                        ],
                        max_length=20,
                    ),
                ),
                ("lifecycle_stage", models.CharField(max_length=100)),
                ("health_status", models.CharField(max_length=100)),
                ("is_pregnant", models.BooleanField(default=False)),
                ("is_lactating", models.BooleanField(default=False)),
                ("is_quarantine", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anminal_breeds",
                        to="admin_panel.breed",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.farm",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="animals.animal",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animals_species",
                        to="admin_panel.species",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="farms.farmunit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
