# Generated by Django 5.2.5 on 2026-09-05 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_panel", "0001_initial"),
        ("core", "0001_initial"),
        ("farms", "0001_initial"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tag_id", models.CharField(blank=True, max_length=100, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("born", "Born on Farm"),
                            ("purchased", "Purchased"),
                            ("imported", "Imported"),
                            ("transferred_in", "Transferred In"),
                            ("donated", "Donated"),
                            ("opening_record", "Opening Record"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("estimated_age_months", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("sold", "Sold"),
                            ("dead", "Dead"),
                            ("transferred_out", "Transferred out"),
                            ("culled", "Culled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("sick", "Sick"),
                            ("recovering", "Recovering"),
                            ("at_risk", "At Risk"),
                        ],
                        default="healthy",
                        max_length=20,
                    ),
                ),
                ("is_pregnant", models.BooleanField(default=False)),
                ("is_lactating", models.BooleanField(default=False)),
                ("is_quarantine", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="animals/"),
                ),
                (
                    "breed_type",
                    models.CharField(
                        choices=[("purebred", "Purebred"), ("crossbred", "Crossbred")],
                        default="purebred",
                        max_length=20,
                    ),
                ),
                (
                    "current_life_stage",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_breeding_restricted", models.BooleanField(default=False)),
                ("breeding_restricted_reason", models.TextField(blank=True, null=True)),
                ("sale_approved", models.BooleanField(default=False)),
                ("sale_approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "breed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="animal_breeds",
                        to="admin_panel.breed",
                    ),
                ),
                (
                    "dam_breed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dam_offspring",
                        to="admin_panel.livestockbreed",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.farm",
                    ),
                ),
                (
                    "housing_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="animals",
                        to="admin_panel.farmhousingunit",
                    ),
                ),
                (
                    "livestock_breed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="animals",
                        to="admin_panel.livestockbreed",
                    ),
                ),
                (
                    "livestock_species",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="animals",
                        to="admin_panel.livestockspecies",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offspring",
                        to="animals.animal",
                    ),
                ),
                (
                    "sale_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sire_breed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sire_offspring",
                        to="admin_panel.livestockbreed",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="animals_species",
                        to="admin_panel.species",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="farms.farmunit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="animals_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnimalDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_animals", models.PositiveIntegerField(default=0)),
                ("active", models.PositiveIntegerField(default=0)),
                ("healthy", models.PositiveIntegerField(default=0)),
                ("lactating", models.PositiveIntegerField(default=0)),
                ("pregnant", models.PositiveIntegerField(default=0)),
                ("sick", models.PositiveIntegerField(default=0)),
                ("quarantine", models.PositiveIntegerField(default=0)),
                ("deaths", models.PositiveIntegerField(default=0)),
                ("sales", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animal_dashboard",
                        to="organization.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Animal Dashboard",
                "verbose_name_plural": "Animal Dashboards",
            },
        ),
        migrations.CreateModel(
            name="AnimalGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animal_groups",
                        to="organization.farm",
                    ),
                ),
                (
                    "group_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.grouptype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateTimeField(db_index=True)),
                ("event_title", models.CharField(max_length=255)),
                ("event_summary", models.TextField(blank=True, null=True)),
                (
                    "reference_table",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reference_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animal_event_animals",
                        to="animals.animal",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="core.eventtype",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animal_event_farms",
                        to="organization.farm",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animal_event_groups",
                        to="animals.animalgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnimalGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("REMOVED", "Removed")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="animals.animal",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="animals.animalgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimalProfileAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attribute_key", models.CharField(max_length=100)),
                ("attribute_value", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_attributes",
                        to="animals.animal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Animal Profile Attribute",
                "verbose_name_plural": "Animal Profile Attributes",
            },
        ),
        migrations.CreateModel(
            name="AnimalWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("weight", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weights",
                        to="animals.animal",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.farm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyMilkSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "total_litres",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_milk_summaries",
                        to="organization.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Milk Summary",
                "verbose_name_plural": "Daily Milk Summaries",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MilkRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_date", models.DateField()),
                (
                    "session",
                    models.CharField(
                        choices=[("morning", "Morning"), ("evening", "Evening")],
                        max_length=10,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=6)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milk_records",
                        to="animals.animal",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_milk_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milk_records",
                        to="organization.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["-record_date"],
            },
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(fields=["farm"], name="animals_ani_farm_id_46c9c7_idx"),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(fields=["status"], name="animals_ani_status_e5c501_idx"),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(
                fields=["health_status"], name="animals_ani_health__f7c454_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animalgroup",
            index=models.Index(
                fields=["farm", "group_type"], name="animals_ani_farm_id_9565ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animalgroup",
            index=models.Index(fields=["status"], name="animals_ani_status_504730_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="animalgroup",
            unique_together={("farm", "name")},
        ),
        migrations.AddIndex(
            model_name="animalevent",
            index=models.Index(
                fields=["farm", "animal"], name="animals_ani_farm_id_a8a0bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animalevent",
            index=models.Index(
                fields=["farm", "group"], name="animals_ani_farm_id_9bee7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animalevent",
            index=models.Index(
                fields=["event_type"], name="animals_ani_event_t_9cb480_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animalevent",
            index=models.Index(
                fields=["event_date"], name="animals_ani_event_d_c9b00f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animalgroupmember",
            index=models.Index(
                fields=["group", "status"], name="animals_ani_group_i_845b6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animalgroupmember",
            index=models.Index(
                fields=["animal", "status"], name="animals_ani_animal__f74c7f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="animalgroupmember",
            unique_together={("group", "animal")},
        ),
        migrations.AddConstraint(
            model_name="animalprofileattribute",
            constraint=models.UniqueConstraint(
                fields=("animal", "attribute_key"), name="unique_animal_attribute"
            ),
        ),
        migrations.AddConstraint(
            model_name="animalweight",
            constraint=models.UniqueConstraint(
                fields=("animal", "date"), name="unique_weight_per_day_per_animal"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailymilksummary",
            unique_together={("farm", "date")},
        ),
        migrations.AddConstraint(
            model_name="milkrecord",
            constraint=models.UniqueConstraint(
                fields=("animal", "record_date", "session"),
                name="unique_milk_record_per_session",
            ),
        ),
    ]
