# Generated by Django 5.2.5 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("animals", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="animalevent",
            name="actor_display_snapshot",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="animalevent",
            name="actor_type",
            field=models.CharField(default="user", max_length=16),
        ),
        migrations.AddField(
            model_name="animalevent",
            name="changeset",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="animalevent",
            name="correlation_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="animalevent",
            name="event_name",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name="animalevent",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="animalevent",
            name="source_module",
            field=models.CharField(default="operations", max_length=64),
        ),
    ]
