# Generated by Django 5.2.5 on 2026-04-25 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0005_animalgroup_animalgroupmember_and_more"),
        ("core", "0003_eventtype_user_grouptype_user"),
        ("organization", "0004_farmtype_industry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateTimeField(db_index=True)),
                ("event_title", models.CharField(max_length=255)),
                ("event_summary", models.TextField(blank=True, null=True)),
                (
                    "reference_table",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reference_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animal_event_animals",
                        to="animals.animal",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="core.eventtype",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animal_event_farms",
                        to="organization.farm",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animal_event_groups",
                        to="animals.animalgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_date"],
                "indexes": [
                    models.Index(
                        fields=["farm", "animal"], name="animals_ani_farm_id_a8a0bd_idx"
                    ),
                    models.Index(
                        fields=["farm", "group"], name="animals_ani_farm_id_9bee7c_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="animals_ani_event_t_9cb480_idx"
                    ),
                    models.Index(
                        fields=["event_date"], name="animals_ani_event_d_c9b00f_idx"
                    ),
                ],
            },
        ),
    ]
