# Generated by Django 5.2.5 on 2026-04-25 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0006_animalevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalevent",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animal_event_groups",
                to="animals.animalgroup",
            ),
        ),
    ]
