# Generated by Django 5.2.5 on 2026-04-28 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0009_animalweight_farm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalevent",
            name="animal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animal_event_animals",
                to="animals.animal",
            ),
        ),
    ]
