# Generated by Django 5.2.5 on 2026-04-28 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_unittype"),
        ("animals", "0010_alter_animalevent_animal"),
        ("farms", "0003_alter_farmunit_unit_type"),
        ("organization", "0004_farmtype_industry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animal",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="animal",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("sold", "Sold"), ("dead", "Dead")],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(fields=["farm"], name="animals_ani_farm_id_46c9c7_idx"),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(fields=["status"], name="animals_ani_status_e5c501_idx"),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(
                fields=["health_status"], name="animals_ani_health__f7c454_idx"
            ),
        ),
    ]
