# Generated by Django 5.2.5 on 2026-05-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0014_animaldashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaldashboard',
            name='vaccination_due',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
