# Generated by Django 5.2.5 on 2026-06-16 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0017_animaldashboard_healthy"),
        ("organization", "0004_farmtype_industry"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMilkSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "total_litres",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_milk_summaries",
                        to="organization.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Milk Summary",
                "verbose_name_plural": "Daily Milk Summaries",
                "ordering": ["-date"],
                "unique_together": {("farm", "date")},
            },
        ),
    ]
