# Generated by Django 5.2.5 on 2026-06-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0018_daily_milk_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="animals/"),
        ),
    ]
