# Generated by Django 5.2.5 on 2026-07-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0025_animal_sale_approved_animal_sale_approved_at_and_more"),
        ("finance", "0003_copy_animal_financial_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="acquisition_cost",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="current_estimated_value",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="opening_value",
        ),
        migrations.DeleteModel(
            name="AnimalAcquisition",
        ),
    ]
