# Generated by Django 5.2.5 on 2026-07-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0026_remove_animal_acquisition_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="classification",
        ),
    ]
