# Generated by Django 5.2.5 on 2026-08-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0027_remove_animal_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("sold", "Sold"),
                    ("dead", "Dead"),
                    ("transferred_out", "Transferred out"),
                    ("culled", "Culled"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="tag_id",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
