# Generated by Django 5.2.5 on 2026-08-31 01:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0028_v21_contract"),
        ("operations", "0001_initial"),
        ("organization", "0005_organization_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="occurrence_key",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name="task",
            name="source_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("schedule", "Schedule"),
                    ("alert", "Alert"),
                    ("health_case", "Health case"),
                    ("health_observation", "Health observation"),
                    ("treatment_follow_up", "Treatment follow-up"),
                    ("reproduction_event", "Reproduction event"),
                    ("inventory_rule", "Inventory rule"),
                    ("system", "System"),
                ],
                default="manual",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="unable_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="unable_reason_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="task",
            name="unable_to_complete_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("assigned", "Assigned"),
                    ("accepted", "Accepted"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("unable_to_complete", "Unable to complete"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("vaccination", "Vaccination"),
                    ("treatment", "Treatment"),
                    ("feed_issuance", "Feed issuance"),
                    ("sale", "Sale"),
                    ("movement", "Movement"),
                    ("observation", "Health observation"),
                    ("weight", "Weight"),
                    ("pregnancy_check", "Pregnancy check"),
                    ("mortality", "Mortality"),
                    ("generic", "Generic"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="taskschedule",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("vaccination", "Vaccination"),
                    ("treatment", "Treatment"),
                    ("feed_issuance", "Feed issuance"),
                    ("sale", "Sale"),
                    ("movement", "Movement"),
                    ("observation", "Health observation"),
                    ("weight", "Weight"),
                    ("pregnancy_check", "Pregnancy check"),
                    ("mortality", "Mortality"),
                    ("generic", "Generic"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("occurrence_key__gt", "")),
                fields=("schedule", "occurrence_key"),
                name="unique_schedule_occurrence",
            ),
        ),
    ]
