# Generated by Django 5.2.5 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("operations", "0002_repair_task_columns")]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(default="system", max_length=64),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "notification_type", "created_at"], name="operations__user_id_ecda38_idx"),
        ),
    ]
