# Generated by Django 5.2.5 on 2026-03-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subcriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="annual_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_batches",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_farms",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_users",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="monthly_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
