# Generated by Django 5.2.5 on 2026-03-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subcriptions", "0002_alter_subscriptionplan_annual_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
