# Generated by Django 5.2.5 on 2026-09-05 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_system", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Drug Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "active_ingredient",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("brand_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "dosage_form",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("injection", "Injection"),
                            ("oral_liquid", "Oral Liquid"),
                            ("powder", "Powder"),
                            ("topical", "Topical"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "strength_concentration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "unit_of_measurement",
                    models.CharField(
                        choices=[
                            ("bottle", "Bottle"),
                            ("vial", "Vial"),
                            ("tablet", "Tablet"),
                            ("sachet", "Sachet"),
                            ("ml", "Millilitre"),
                            ("litre", "Litre"),
                            ("gram", "Gram"),
                            ("kg", "Kilogram"),
                            ("dose", "Dose"),
                        ],
                        max_length=10,
                    ),
                ),
                ("withdrawal_period_days", models.PositiveIntegerField(default=0)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_drugs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_drugs",
                        to="organization.farm",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drugs",
                        to="pharmacy.drugcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DrugBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=100)),
                (
                    "quantity_received",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "quantity_available",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "purchase_unit",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "cost_per_base_unit",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("supplier", models.CharField(blank=True, max_length=200, null=True)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("manufacturing_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField()),
                (
                    "storage_location",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "minimum_stock_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("depleted", "Depleted"),
                            ("recalled", "Recalled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True, null=True, upload_to="pharmacy/documents/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_drug_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="pharmacy.drug",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drug_batches",
                        to="organization.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date"],
                "indexes": [
                    models.Index(
                        fields=["farm", "status"], name="pharmacy_dr_farm_id_7fef39_idx"
                    ),
                    models.Index(
                        fields=["expiry_date"], name="pharmacy_dr_expiry__352f43_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("drug", "farm", "batch_number"),
                        name="unique_batch_per_drug_farm",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="drug",
            constraint=models.UniqueConstraint(
                fields=("farm", "name"), name="unique_drug_per_farm"
            ),
        ),
    ]
