# Generated by Django 5.2.5 on 2026-09-05 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_panel", "0001_initial"),
        ("animals", "0001_initial"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_system", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Feed Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FeedBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=100)),
                (
                    "purchase_unit",
                    models.CharField(
                        choices=[
                            ("bag", "Bag"),
                            ("kg", "Kilogram"),
                            ("tonne", "Tonne"),
                            ("bale", "Bale"),
                            ("sack", "Sack"),
                            ("litre", "Litre"),
                            ("container", "Container"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("package_size", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "number_of_packages",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_quantity_base_unit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "quantity_available",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "cost_per_package",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "cost_per_base_unit",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("supplier", models.CharField(blank=True, max_length=200, null=True)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "storage_location",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "minimum_stock_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("depleted", "Depleted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True, null=True, upload_to="feed/documents/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_feed_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_batches",
                        to="organization.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date"],
            },
        ),
        migrations.CreateModel(
            name="FeedInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_name", models.CharField(max_length=255)),
                (
                    "quantity_available",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("unit", models.CharField(max_length=50)),
                (
                    "reorder_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("low_stock", "Low Stock"),
                            ("out_of_stock", "Out of Stock"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("last_restocked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_inventories",
                        to="organization.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["feed_name"],
            },
        ),
        migrations.CreateModel(
            name="FeedIssuanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("animal", "Animal"), ("group", "Group")],
                        max_length=10,
                    ),
                ),
                (
                    "quantity_issued",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("issue_date", models.DateField()),
                (
                    "feeding_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                            ("full_day", "Full Day"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "allocation_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("equal", "Equal allocation per animal"),
                            ("weight_based", "Allocation based on animal weight"),
                            (
                                "consumption_based",
                                "Allocation based on estimated consumption",
                            ),
                            ("life_stage_based", "Allocation based on life stage"),
                            ("manual", "Manual allocation"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feed_issuances",
                        to="animals.animal",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_issuance_records",
                        to="organization.farm",
                    ),
                ),
                (
                    "fed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fed_feed_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feed_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issuance_records",
                        to="feed.feedbatch",
                    ),
                ),
                (
                    "feed_inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issuance_records",
                        to="feed.feedinventory",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feed_issuances",
                        to="animals.animalgroup",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_feed_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="FeedCostAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "allocated_cost",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_cost_allocations",
                        to="animals.animal",
                    ),
                ),
                (
                    "feed_issuance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="feed.feedissuancerecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedConfirmationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual_used_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("confirmation_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "variance_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("variance_detected", "Variance Detected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_feed_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_confirmations",
                        to="organization.farm",
                    ),
                ),
                (
                    "issuance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmation",
                        to="feed.feedissuancerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-confirmation_date"],
            },
        ),
        migrations.CreateModel(
            name="FeedPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("species", "Species"), ("group", "Group")],
                        max_length=10,
                    ),
                ),
                (
                    "daily_feed_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("unit", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("completed", "Completed"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_feed_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_plans",
                        to="organization.farm",
                    ),
                ),
                (
                    "feed_inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_plans",
                        to="feed.feedinventory",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feed_plans",
                        to="animals.animalgroup",
                    ),
                ),
                (
                    "livestock_species",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feed_plans",
                        to="admin_panel.livestockspecies",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feed_plans",
                        to="admin_panel.species",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="FeedType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feed_types",
                        to="feed.feedcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_feed_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_feed_types",
                        to="organization.farm",
                    ),
                ),
                (
                    "species",
                    models.ManyToManyField(
                        blank=True,
                        related_name="feed_types",
                        to="admin_panel.livestockspecies",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="feedinventory",
            name="feed_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventories",
                to="feed.feedtype",
            ),
        ),
        migrations.AddField(
            model_name="feedbatch",
            name="feed_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="feed.feedtype",
            ),
        ),
        migrations.CreateModel(
            name="FeedUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "abbreviation",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_feed_units",
                        to="organization.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="feedinventory",
            name="feed_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventories",
                to="feed.feedunit",
            ),
        ),
        migrations.AddField(
            model_name="feedbatch",
            name="base_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feed_batches",
                to="feed.feedunit",
            ),
        ),
        migrations.AddIndex(
            model_name="feedissuancerecord",
            index=models.Index(
                fields=["farm", "issue_date"], name="feed_feedis_farm_id_a544a0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="feedcostallocation",
            constraint=models.UniqueConstraint(
                fields=("feed_issuance", "animal"),
                name="unique_allocation_per_issuance_animal",
            ),
        ),
        migrations.AddIndex(
            model_name="feedplan",
            index=models.Index(
                fields=["farm", "status"], name="feed_feedpl_farm_id_ce67ac_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="feedtype",
            constraint=models.UniqueConstraint(
                fields=("farm", "name"), name="unique_feed_type_per_farm"
            ),
        ),
        migrations.AddConstraint(
            model_name="feedunit",
            constraint=models.UniqueConstraint(
                fields=("farm", "name"), name="unique_feed_unit_per_farm"
            ),
        ),
        migrations.AddIndex(
            model_name="feedinventory",
            index=models.Index(
                fields=["farm", "status"], name="feed_feedin_farm_id_d23717_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="feedinventory",
            constraint=models.UniqueConstraint(
                fields=("farm", "feed_name"), name="unique_feed_per_farm"
            ),
        ),
        migrations.AddIndex(
            model_name="feedbatch",
            index=models.Index(
                fields=["farm", "status"], name="feed_feedba_farm_id_52a587_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="feedbatch",
            constraint=models.UniqueConstraint(
                fields=("feed_type", "farm", "batch_number"),
                name="unique_feed_batch_per_type_farm",
            ),
        ),
    ]
