# Generated by Django 5.2.5 on 2026-04-28 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0004_farmtype_industry"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_name", models.CharField(max_length=255)),
                (
                    "quantity_available",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("unit", models.CharField(max_length=50)),
                (
                    "reorder_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("low_stock", "Low Stock"),
                            ("out_of_stock", "Out of Stock"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("last_restocked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_inventories",
                        to="organization.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["feed_name"],
                "indexes": [
                    models.Index(
                        fields=["farm", "status"], name="feed_feedin_farm_id_d23717_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("farm", "feed_name"), name="unique_feed_per_farm"
                    )
                ],
            },
        ),
    ]
