# Generated by Django 5.2.5 on 2026-07-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_livestock_master_data"),
        ("feed", "0004_feedconfirmationrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedplan",
            name="livestock_species",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feed_plans",
                to="admin_panel.livestockspecies",
            ),
        ),
    ]
