# Generated by Django 5.2.5 on 2026-07-25 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0006_feed_master_data"),
        ("organization", "0004_farmtype_industry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=100)),
                (
                    "purchase_unit",
                    models.CharField(
                        choices=[
                            ("bag", "Bag"),
                            ("kg", "Kilogram"),
                            ("tonne", "Tonne"),
                            ("bale", "Bale"),
                            ("sack", "Sack"),
                            ("litre", "Litre"),
                            ("container", "Container"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("package_size", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "number_of_packages",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_quantity_base_unit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "quantity_available",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "cost_per_package",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "cost_per_base_unit",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("supplier", models.CharField(blank=True, max_length=200, null=True)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "storage_location",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "minimum_stock_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("depleted", "Depleted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True, null=True, upload_to="feed/documents/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "base_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feed_batches",
                        to="feed.feedunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_feed_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_batches",
                        to="organization.farm",
                    ),
                ),
                (
                    "feed_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="feed.feedtype",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date"],
                "indexes": [
                    models.Index(
                        fields=["farm", "status"], name="feed_feedba_farm_id_52a587_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feed_type", "farm", "batch_number"),
                        name="unique_feed_batch_per_type_farm",
                    )
                ],
            },
        ),
    ]
