# Generated by Django 5.2.5 on 2026-07-25 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0025_animal_sale_approved_animal_sale_approved_at_and_more"),
        ("feed", "0007_feedbatch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedissuancerecord",
            name="allocation_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("equal", "Equal allocation per animal"),
                    ("weight_based", "Allocation based on animal weight"),
                    ("consumption_based", "Allocation based on estimated consumption"),
                    ("life_stage_based", "Allocation based on life stage"),
                    ("manual", "Manual allocation"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feedissuancerecord",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="feedissuancerecord",
            name="fed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fed_feed_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedissuancerecord",
            name="feed_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issuance_records",
                to="feed.feedbatch",
            ),
        ),
        migrations.AddField(
            model_name="feedissuancerecord",
            name="feeding_period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("morning", "Morning"),
                    ("afternoon", "Afternoon"),
                    ("evening", "Evening"),
                    ("full_day", "Full Day"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="FeedCostAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "allocated_cost",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_cost_allocations",
                        to="animals.animal",
                    ),
                ),
                (
                    "feed_issuance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="feed.feedissuancerecord",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feed_issuance", "animal"),
                        name="unique_allocation_per_issuance_animal",
                    )
                ],
            },
        ),
    ]
