# Generated by Django 5.2.5 on 2026-04-26 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0007_alter_animalevent_group"),
        ("organization", "0004_farmtype_industry"),
        ("reproduction", "0003_pregnancyrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BirthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_date", models.DateField()),
                ("number_of_offspring", models.PositiveIntegerField()),
                ("number_alive", models.PositiveIntegerField()),
                ("number_dead", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="pregnancyrecord",
            constraint=models.UniqueConstraint(
                fields=("farm", "animal"), name="unique_pregnancy_per_animal_per_farm"
            ),
        ),
        migrations.AddField(
            model_name="birthrecord",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="birthrecord",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="organization.farm"
            ),
        ),
        migrations.AddField(
            model_name="birthrecord",
            name="mother",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="animals.animal"
            ),
        ),
    ]
