# Generated by Django 5.2.5 on 2026-03-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminlevel1",
            name="timezone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
