# Generated by Django 5.2.5 on 2026-09-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_avatar_user_deactivated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshsession',
            name='channel',
            field=models.CharField(default='web', max_length=10),
        ),
    ]
