# Generated by Django 5.2.5 on 2026-03-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_user_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Suspended", "Suspended"),
                    ("Deleted", "Deleted"),
                    ("inactive", "Inactive"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
    ]
