# Generated by Django 5.2.5 on 2026-04-10 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_unittype"),
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="lifecycle_stage",
        ),
        migrations.AlterField(
            model_name="animal",
            name="breed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animal_breeds",
                to="admin_panel.breed",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="health_status",
            field=models.CharField(
                choices=[
                    ("healthy", "Healthy"),
                    ("sick", "Sick"),
                    ("recovering", "Recovering"),
                    ("at_risk", "At Risk"),
                ],
                default="healthy",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offspring",
                to="animals.animal",
            ),
        ),
    ]
