# Generated by Django 5.2.5 on 2026-04-10 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_remove_animal_lifecycle_stage_alter_animal_breed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="animals_added_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
