# Generated by Django 5.2.5 on 2026-04-17 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0003_animal_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalProfileAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attribute_key", models.CharField(max_length=100)),
                ("attribute_value", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_attributes",
                        to="animals.animal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Animal Profile Attribute",
                "verbose_name_plural": "Animal Profile Attributes",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("animal", "attribute_key"),
                        name="unique_animal_attribute",
                    )
                ],
            },
        ),
    ]
