# Generated by Django 5.2.5 on 2026-04-22 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0004_animalprofileattribute"),
        ("core", "0001_initial"),
        ("organization", "0004_farmtype_industry"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animal_groups",
                        to="organization.farm",
                    ),
                ),
                (
                    "group_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.grouptype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimalGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("REMOVED", "Removed")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="animals.animal",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="animals.animalgroup",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="animalgroup",
            index=models.Index(
                fields=["farm", "group_type"], name="animals_ani_farm_id_9565ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animalgroup",
            index=models.Index(fields=["status"], name="animals_ani_status_504730_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="animalgroup",
            unique_together={("farm", "name")},
        ),
        migrations.AddIndex(
            model_name="animalgroupmember",
            index=models.Index(
                fields=["group", "status"], name="animals_ani_group_i_845b6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animalgroupmember",
            index=models.Index(
                fields=["animal", "status"], name="animals_ani_animal__f74c7f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="animalgroupmember",
            unique_together={("group", "animal")},
        ),
    ]
