# Generated by Django 5.2.5 on 2026-04-27 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0008_animalweight"),
        ("organization", "0004_farmtype_industry"),
    ]

    operations = [
        migrations.AddField(
            model_name="animalweight",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.farm",
            ),
        ),
    ]
