# Generated by Django 5.2.5 on 2026-04-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0012_milkrecord"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animalevent",
            options={"ordering": ["-created_at"]},
        ),
    ]
