# Generated by Django 5.2.5 on 2026-05-26 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0013_alter_animalevent_options'),
        ('organization', '0004_farmtype_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_animals', models.PositiveIntegerField(default=0)),
                ('active', models.PositiveIntegerField(default=0)),
                ('lactating', models.PositiveIntegerField(default=0)),
                ('pregnant', models.PositiveIntegerField(default=0)),
                ('sick', models.PositiveIntegerField(default=0)),
                ('quarantine', models.PositiveIntegerField(default=0)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('sales', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='animal_dashboard', to='organization.farm')),
            ],
            options={
                'verbose_name': 'Animal Dashboard',
                'verbose_name_plural': 'Animal Dashboards',
            },
        ),
    ]
