# Generated by Django 5.2.5 on 2026-05-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0015_animaldashboard_vaccination_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaldashboard',
            name='vaccination_due',
        ),
    ]
