# Generated by Django 5.2.5 on 2026-05-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0016_remove_animaldashboard_vaccination_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaldashboard',
            name='healthy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
