# Generated by Django 5.2.5 on 2026-07-16 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_livestock_master_data"),
        ("animals", "0019_add_image_to_animal"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="animals",
                to="admin_panel.animalclassification",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="housing_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="animals",
                to="admin_panel.farmhousingunit",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="livestock_breed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="animals",
                to="admin_panel.livestockbreed",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="livestock_species",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="animals",
                to="admin_panel.livestockspecies",
            ),
        ),
    ]
