# Generated by Django 5.2.5 on 2026-07-17 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0005_newsletter_subscriber"),
        ("animals", "0020_add_livestock_master_fks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="breed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="animal_breeds",
                to="admin_panel.breed",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="species",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="animals_species",
                to="admin_panel.species",
            ),
        ),
    ]
