# Generated by Django 5.2.5 on 2026-07-17 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0021_make_legacy_species_breed_nullable"),
        ("farms", "0003_alter_farmunit_unit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="farms.farmunit",
            ),
        ),
    ]
