# Generated by Django 5.2.5 on 2026-07-25 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0005_newsletter_subscriber"),
        ("animals", "0022_make_unit_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="acquisition_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="breed_type",
            field=models.CharField(
                choices=[("purebred", "Purebred"), ("crossbred", "Crossbred")],
                default="purebred",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="current_estimated_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="dam_breed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dam_offspring",
                to="admin_panel.livestockbreed",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="opening_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="sire_breed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sire_offspring",
                to="admin_panel.livestockbreed",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("born", "Born on Farm"),
                    ("purchased", "Purchased"),
                    ("imported", "Imported"),
                    ("transferred_in", "Transferred In"),
                    ("donated", "Donated"),
                    ("opening_record", "Opening Record"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AnimalAcquisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(default="NGN", max_length=10)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("pending", "Pending"),
                            ("partial", "Partial"),
                        ],
                        default="paid",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "transaction_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True, null=True, upload_to="animals/acquisition/"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "transportation_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "veterinary_inspection_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "other_acquisition_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("import_date", models.DateField(blank=True, null=True)),
                (
                    "shipping_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "customs_clearance_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "quarantine_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "veterinary_certification_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "insurance_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "other_import_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "production_cost_dam_feeding",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "production_cost_pregnancy_treatment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "production_cost_delivery",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "production_cost_breeding",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "estimated_opening_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("valuation_date", models.DateField(blank=True, null=True)),
                (
                    "valuation_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("market_comparison", "Market Comparison"),
                            ("book_value", "Book Value"),
                            ("professional_appraisal", "Professional Appraisal"),
                            ("owner_estimate", "Owner Estimate"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("valuation_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "animal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acquisition",
                        to="animals.animal",
                    ),
                ),
            ],
        ),
    ]
