# Generated by Django 5.2.5 on 2026-07-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0023_animal_acquisition_cost_animal_breed_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="breeding_restricted_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="current_life_stage",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="is_breeding_restricted",
            field=models.BooleanField(default=False),
        ),
    ]
