# Generated by Django 5.2.5 on 2026-07-25 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0024_animal_breeding_restricted_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="sale_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animal",
            name="sale_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="sale_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
