# Generated by Django 5.2.5 on 2026-04-25 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_eventtype_user_grouptype_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventtype",
            name="description",
        ),
        migrations.RemoveField(
            model_name="eventtype",
            name="user",
        ),
    ]
