# Generated by Django 5.2.5 on 2026-07-25 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0006_animallifecyclehistory_lifestagedefinition"),
        ("organization", "0004_farmtype_industry"),
        ("reproduction", "0005_birthoffspringrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreedingEligibilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_breeding_age_months", models.FloatField(blank=True, null=True)),
                (
                    "recommended_breeding_age_months",
                    models.FloatField(blank=True, null=True),
                ),
                ("max_breeding_age_months", models.FloatField(blank=True, null=True)),
                ("min_breeding_weight_kg", models.FloatField(blank=True, null=True)),
                (
                    "min_postpartum_interval_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_births_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("allow_pregnant_and_lactating", models.BooleanField(default=True)),
                ("is_system", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breeding_rules",
                        to="admin_panel.livestockbreed",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breeding_rules",
                        to="organization.farm",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breeding_rules",
                        to="admin_panel.livestockspecies",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("species", "breed", "farm"),
                        name="unique_breeding_rule_scope",
                    )
                ],
            },
        ),
    ]
